services:
  ecosena-db:
    image: mysql:8.4
    container_name: ecosena_mysql
    ports:
      - "3306:3306" 
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ecosena_mysql_data:/var/lib/mysql 
    networks:
      - ecosena_backend

  senasofia-db:
    image: mysql:8.4
    container_name: senasofia_mysql
    ports:
      - "3309:3306" 
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_SENA_DATABASE}
      MYSQL_USER: ${MYSQL_SENA_USER}
      MYSQL_PASSWORD: ${MYSQL_SENA_PASSWORD}
    volumes:
      - sofiasena_mysql_data:/var/lib/mysql
    networks:
      - ecosena_backend

  ecosena-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecosena_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConn=Server=ecosena-db;Port=3306;Database=${MYSQL_DATABASE};User=${MYSQL_USER};Password=${MYSQL_PASSWORD}
      - ConnectionStrings__SenaConn=Server=senasofia-db;Port=3306;Database=${MYSQL_SENA_DATABASE};User=${MYSQL_SENA_USER};Password=${MYSQL_SENA_PASSWORD}
      - JwtConfig__Key=${JWT_KEY}
      - JwtConfig__Issuer=${JWT_ISSUER}
      - JwtConfig__Audience=${JWT_AUDIENCE}
      - JwtConfig__TokenValidityMins=${JWT_VALIDITY_MINS}
      - APRENDIZ_PASSWORD=${APRENDIZ_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD} 
      - Cloudinary__CloudName=${CLOUD_NAME}
      - Cloudinary__ApiKey=${CLOUD_API_KEY}
      - Cloudinary__ApiSecret=${CLOUD_API_SECRET}
    depends_on:
      - ecosena-db
      - senasofia-db 
    networks:
      - ecosena_backend

volumes:
  ecosena_mysql_data:
  sofiasena_mysql_data:

networks:
  ecosena_backend:
    driver: bridge