// <auto-generated />
using System;
using EcoSENA.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoSENA.Api.Migrations
{
    [DbContext(typeof(EcosenaDbContext))]
    [Migration("20260604151914_CloudinaryUpdt")]
    partial class CloudinaryUpdt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcoSENA.Api.Entities.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("Portada")
                        .HasColumnType("longtext")
                        .HasColumnName("portada");

                    b.Property<int>("RedactorId")
                        .HasColumnType("int")
                        .HasColumnName("id_redactor");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("RedactorId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Entregada")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("entregada");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_envio");

                    b.Property<bool>("Leida")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("leida");

                    b.Property<int>("ReporteId")
                        .HasColumnType("int")
                        .HasColumnName("id_reporte");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AprendizId")
                        .HasColumnType("int")
                        .HasColumnName("id_aprendiz");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_publicacion");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_revision");

                    b.Property<DateTime?>("FechaSolucion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_solucion");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("foto");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("titulo");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ubicacion");

                    b.HasKey("Id");

                    b.HasIndex("AprendizId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("ContraseñaHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("documento");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<int?>("Ficha")
                        .HasColumnType("int")
                        .HasColumnName("ficha");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("foto_perfil");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("ProgramaFormacion")
                        .HasColumnType("longtext")
                        .HasColumnName("programa_formacion");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Bohorquez",
                            ContraseñaHash = "$2a$11$FRnXpBy8v3wzeteLFtOxuORpqSzTm3zsRYiLJSKdx98/e9zkyJA8W",
                            Correo = "juan_bquez@soy.sena.edu.co",
                            Documento = "0123456789",
                            Ficha = 333333,
                            FotoPerfil = "https://res.cloudinary.com/denixbxml/image/upload/v1780584233/pfp_yutpht.png",
                            Nombre = "Juan",
                            ProgramaFormacion = "ADSO",
                            Rol = "Aprendiz"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Nasraoui Ebana",
                            ContraseñaHash = "$2a$11$Dcxvo2hDC.wg/H9gC0induOFQcnW4HJQ5HF9V.EmX2/m5qNdzkU9a",
                            Correo = "lamine_yamal@sena.edu.co",
                            Documento = "1111111111",
                            FechaNacimiento = new DateOnly(2007, 7, 13),
                            FotoPerfil = "https://res.cloudinary.com/denixbxml/image/upload/v1780584233/pfp_yutpht.png",
                            Nombre = "Lamine Yamal",
                            Rol = "Administrador"
                        });
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Entrada", b =>
                {
                    b.HasOne("EcoSENA.Api.Entities.Usuario", "Redactor")
                        .WithMany()
                        .HasForeignKey("RedactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Redactor");
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Notificacion", b =>
                {
                    b.HasOne("EcoSENA.Api.Entities.Reporte", "Reporte")
                        .WithMany()
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoSENA.Api.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Reporte", b =>
                {
                    b.HasOne("EcoSENA.Api.Entities.Usuario", "Aprendiz")
                        .WithMany()
                        .HasForeignKey("AprendizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aprendiz");
                });
#pragma warning restore 612, 618
        }
    }
}
