// <auto-generated />
using System;
using EcoSENA.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoSENA.Api.Migrations
{
    [DbContext(typeof(EcosenaDbContext))]
    [Migration("20260518214311_AddNewColumns")]
    partial class AddNewColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcoSENA.Api.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("ContraseñaHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("documento");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<int?>("Ficha")
                        .HasColumnType("int")
                        .HasColumnName("ficha");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext")
                        .HasColumnName("foto_perfil");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("ProgramaFormacion")
                        .HasColumnType("longtext")
                        .HasColumnName("programa_formacion");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Bohorquez",
                            ContraseñaHash = "$2a$11$XIEjdiSl7htcAYpTvQo.YuHLFCKhlPIbx9mDXN70Jr0xUqax4qKAC",
                            Correo = "juan_bquez@soy.sena.edu.co",
                            Documento = "0123456789",
                            FechaNacimiento = new DateOnly(1, 1, 1),
                            Ficha = 333333,
                            Nombre = "Juan",
                            ProgramaFormacion = "ADSO",
                            Rol = "Aprendiz"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Nasraoui Ebana",
                            ContraseñaHash = "$2a$11$lAt1.J6Au.3Rs2y4EnBwPeGq3kwhh/A6EBCN1QjCuk/7O5bO2MTGy",
                            Correo = "lamine_yamal@sena.edu.co",
                            Documento = "1111111111",
                            FechaNacimiento = new DateOnly(2007, 7, 13),
                            Nombre = "Lamine Yamal",
                            Rol = "Administrador"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
