// <auto-generated />
using System;
using EcoSENA.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoSENA.Api.Migrations.Sofia
{
    [DbContext(typeof(SofiaDbContext))]
    [Migration("20260515193222_GenerateUser")]
    partial class GenerateUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcoSENA.Api.Entities.Sofia.SofiaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("documento");

                    b.Property<string>("EmailPersonal")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("correo_contacto");

                    b.Property<string>("EmailSena")
                        .HasColumnType("longtext")
                        .HasColumnName("correo_institucional");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Documento = "000001",
                            EmailPersonal = "lionel.messi@gmail.com",
                            EmailSena = "lionel_andresmessi@sena.edu.co",
                            FechaNacimiento = new DateOnly(1987, 6, 24),
                            Nombre = "Lionel Andres Messi Cuccittini"
                        },
                        new
                        {
                            Id = 2,
                            Documento = "000002",
                            EmailPersonal = "ronaldo.cris@yahoo.com",
                            EmailSena = "cristiano_dsantos@soy.sena.edu.co",
                            FechaNacimiento = new DateOnly(1985, 2, 5),
                            Nombre = "Cristiano Ronaldo dos Santos Aveiro"
                        },
                        new
                        {
                            Id = 3,
                            Documento = "000003",
                            EmailPersonal = "neymar_jr@gmail.com",
                            EmailSena = "lionel_andresmessi@sena.edu.co",
                            FechaNacimiento = new DateOnly(1992, 2, 5),
                            Nombre = "Neymar da Silva Santos Junior"
                        },
                        new
                        {
                            Id = 4,
                            Documento = "000004",
                            EmailPersonal = "lewan.robert@gmail.com",
                            EmailSena = "robert_lewandowski@soy.sena.edu.co",
                            FechaNacimiento = new DateOnly(1988, 8, 21),
                            Nombre = "Robert Lewandowski"
                        },
                        new
                        {
                            Id = 5,
                            Documento = "000005",
                            EmailPersonal = "juanfer10@gmail.com",
                            EmailSena = "juanfer_quintero@sena.edu.co",
                            FechaNacimiento = new DateOnly(1993, 1, 18),
                            Nombre = "Juan Fernando Quintero Paniagua"
                        },
                        new
                        {
                            Id = 6,
                            Documento = "000006",
                            EmailPersonal = "mbappe@yahoo.com",
                            FechaNacimiento = new DateOnly(1998, 12, 20),
                            Nombre = "Kylian Mbappé Lottin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
