// <auto-generated />
using System;
using EcoSENA.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoSENA.Api.Migrations.Sofia
{
    [DbContext(typeof(SofiaDbContext))]
    partial class SofiaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcoSENA.Api.Entities.Sofia.Ficha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("numero");

                    b.Property<int>("ProgramaFormacionId")
                        .HasColumnType("int")
                        .HasColumnName("id_programa_formacion");

                    b.HasKey("Id");

                    b.HasIndex("ProgramaFormacionId");

                    b.ToTable("Ficha");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Numero = 333333,
                            ProgramaFormacionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Numero = 333334,
                            ProgramaFormacionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Numero = 333344,
                            ProgramaFormacionId = 3
                        });
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Sofia.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AprendizId")
                        .HasColumnType("int")
                        .HasColumnName("id_aprendiz");

                    b.Property<int>("FichaId")
                        .HasColumnType("int")
                        .HasColumnName("id_ficha");

                    b.HasKey("Id");

                    b.HasIndex("AprendizId");

                    b.HasIndex("FichaId");

                    b.ToTable("Matricula");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AprendizId = 2,
                            FichaId = 2
                        },
                        new
                        {
                            Id = 3,
                            AprendizId = 4,
                            FichaId = 3
                        });
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Sofia.ProgramaFormacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("ProgramasFormacion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "ADSO"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Electricidad Industrial"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Animación 3D"
                        });
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Sofia.SofiaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("documento");

                    b.Property<string>("EmailPersonal")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("correo_contacto");

                    b.Property<string>("EmailSena")
                        .HasColumnType("longtext")
                        .HasColumnName("correo_institucional");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Documento = "000001",
                            EmailPersonal = "lionel.messi@gmail.com",
                            EmailSena = "lionel_andresmessi@sena.edu.co",
                            FechaNacimiento = new DateOnly(1987, 6, 24),
                            Nombre = "Lionel Andres Messi Cuccittini"
                        },
                        new
                        {
                            Id = 2,
                            Documento = "000002",
                            EmailPersonal = "ronaldo.cris@yahoo.com",
                            EmailSena = "cristiano_dsantos@soy.sena.edu.co",
                            FechaNacimiento = new DateOnly(1985, 2, 5),
                            Nombre = "Cristiano Ronaldo dos Santos Aveiro"
                        },
                        new
                        {
                            Id = 3,
                            Documento = "000003",
                            EmailPersonal = "neymar_jr@gmail.com",
                            EmailSena = "lionel_andresmessi@sena.edu.co",
                            FechaNacimiento = new DateOnly(1992, 2, 5),
                            Nombre = "Neymar da Silva Santos Junior"
                        },
                        new
                        {
                            Id = 4,
                            Documento = "000004",
                            EmailPersonal = "lewan.robert@gmail.com",
                            EmailSena = "robert_lewandowski@soy.sena.edu.co",
                            FechaNacimiento = new DateOnly(1988, 8, 21),
                            Nombre = "Robert Lewandowski"
                        },
                        new
                        {
                            Id = 5,
                            Documento = "000005",
                            EmailPersonal = "juanfer10@gmail.com",
                            EmailSena = "juanfer_quintero@sena.edu.co",
                            FechaNacimiento = new DateOnly(1993, 1, 18),
                            Nombre = "Juan Fernando Quintero Paniagua"
                        },
                        new
                        {
                            Id = 6,
                            Documento = "000006",
                            EmailPersonal = "mbappe@yahoo.com",
                            FechaNacimiento = new DateOnly(1998, 12, 20),
                            Nombre = "Kylian Mbappé Lottin"
                        });
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Sofia.Ficha", b =>
                {
                    b.HasOne("EcoSENA.Api.Entities.Sofia.ProgramaFormacion", "ProgramaFormacion")
                        .WithMany("Fichas")
                        .HasForeignKey("ProgramaFormacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramaFormacion");
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Sofia.Matricula", b =>
                {
                    b.HasOne("EcoSENA.Api.Entities.Sofia.SofiaUsuario", "Aprendiz")
                        .WithMany("Matriculas")
                        .HasForeignKey("AprendizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoSENA.Api.Entities.Sofia.Ficha", "Ficha")
                        .WithMany("Matriculas")
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aprendiz");

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Sofia.Ficha", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Sofia.ProgramaFormacion", b =>
                {
                    b.Navigation("Fichas");
                });

            modelBuilder.Entity("EcoSENA.Api.Entities.Sofia.SofiaUsuario", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
